package com2002;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com2002.models.Patient;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aca14ams
 */
public class LookUpPatient extends javax.swing.JFrame {

    /**
     * Creates new form LookUpPatient
     */
    public LookUpPatient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        LookUpPatientPanel = new javax.swing.JPanel();
        Lbl_LookUpPatient_Forename = new javax.swing.JLabel();
        TxtFld_LookUpPatient_Forename = new javax.swing.JTextField();
        Lbl_LookUpPatient_Surname = new javax.swing.JLabel();
        TxtFld_LookUpPatient_Surname = new javax.swing.JTextField();
        Lbl_LookUpPatient_Dob = new javax.swing.JLabel();
        TxtFld_LookUpPatient_Dob = new javax.swing.JTextField();
        Lbl_LookUpPatient_Postcode = new javax.swing.JLabel();
        TxtFld_LookUpPatient_Postcode = new javax.swing.JTextField();
        Btn_LookUpPatient_Submit = new javax.swing.JButton();
        Btn_LookUpPatient_Submit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lookup Patient");

        Lbl_LookUpPatient_Forename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_LookUpPatient_Forename.setText("Forename");
        Lbl_LookUpPatient_Forename.setName(""); // NOI18N

        Lbl_LookUpPatient_Surname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_LookUpPatient_Surname.setText("Surname");

        Lbl_LookUpPatient_Dob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_LookUpPatient_Dob.setText("Date of Birth");

        Lbl_LookUpPatient_Postcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_LookUpPatient_Postcode.setText("Postcode");

        Btn_LookUpPatient_Submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_LookUpPatient_Submit.setText("Submit");
        Btn_LookUpPatient_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LookUpPatient_SubmitActionPerformed(evt);
            }
        });

        Btn_LookUpPatient_Submit1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_LookUpPatient_Submit1.setText("Cancel");
        Btn_LookUpPatient_Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LookUpPatient_Submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LookUpPatientPanelLayout = new javax.swing.GroupLayout(LookUpPatientPanel);
        LookUpPatientPanel.setLayout(LookUpPatientPanelLayout);
        LookUpPatientPanelLayout.setHorizontalGroup(
                LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LookUpPatientPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPatientPanelLayout.createSequentialGroup()
                                                .addComponent(Lbl_LookUpPatient_Postcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtFld_LookUpPatient_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPatientPanelLayout.createSequentialGroup()
                                                .addComponent(Lbl_LookUpPatient_Dob)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtFld_LookUpPatient_Dob, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPatientPanelLayout.createSequentialGroup()
                                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Lbl_LookUpPatient_Forename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Lbl_LookUpPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TxtFld_LookUpPatient_Forename)
                                                        .addComponent(TxtFld_LookUpPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 10, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPatientPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_LookUpPatient_Submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_LookUpPatient_Submit1)
                                .addContainerGap())
        );
        LookUpPatientPanelLayout.setVerticalGroup(
                LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LookUpPatientPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_LookUpPatient_Forename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_LookUpPatient_Forename))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_LookUpPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_LookUpPatient_Surname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_LookUpPatient_Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_LookUpPatient_Dob))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_LookUpPatient_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_LookUpPatient_Postcode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LookUpPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Btn_LookUpPatient_Submit)
                                        .addComponent(Btn_LookUpPatient_Submit1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LookUpPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LookUpPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void Btn_LookUpPatient_SubmitActionPerformed(java.awt.event.ActionEvent evt) {
        PatientView view = new PatientView();
        view.setVisible(true);

        String forename = TxtFld_LookUpPatient_Forename.getText();
        System.out.println(forename);
        String surname = TxtFld_LookUpPatient_Surname.getText();
        System.out.println(surname);
        String dobString = TxtFld_LookUpPatient_Dob.getText();
        System.out.println(dobString);
        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        String postcode = TxtFld_LookUpPatient_Postcode.getText();
        System.out.println(postcode);
        try {
            //TODO IT WORKS IT WORKS - NEED TO VALIDATE INPUTS HOWEVER
            Date dob = fmt.parse(dobString);
            System.out.println(dob);
            ArrayList<Patient> patients = Patient.findPatients(forename,surname,dob);
            System.out.println(patients.size());
            for (int i=0;i<patients.size();i++) {
                if (postcode.equals(patients.get(i).getAddress().getPostcode())) {
                    view.setPatient(patients.get(i));
                    System.out.println(patients.get(i).getForename());
                }
                else {
                    //TODO error message?
                    System.out.println(patients.get(i).getSurname());
                }
            }

        } catch (ParseException ex) {
            Logger.getLogger(SecretaryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
//       setVisible(false);
    }

    private void Btn_LookUpPatient_Submit1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //take to calendar
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LookUpPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LookUpPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LookUpPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LookUpPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LookUpPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Btn_LookUpPatient_Submit;
    private javax.swing.JButton Btn_LookUpPatient_Submit1;
    private javax.swing.JLabel Lbl_LookUpPatient_Dob;
    private javax.swing.JLabel Lbl_LookUpPatient_Forename;
    private javax.swing.JLabel Lbl_LookUpPatient_Postcode;
    private javax.swing.JLabel Lbl_LookUpPatient_Surname;
    private javax.swing.JPanel LookUpPatientPanel;
    private javax.swing.JTextField TxtFld_LookUpPatient_Dob;
    private javax.swing.JTextField TxtFld_LookUpPatient_Forename;
    private javax.swing.JTextField TxtFld_LookUpPatient_Postcode;
    private javax.swing.JTextField TxtFld_LookUpPatient_Surname;
    // End of variables declaration
}
