/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com2002;

import com2002.models.Appointment;
import com2002.models.Treatment;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;

/**
 *
 * @author Abigail
 */
public class RecordTreatment extends javax.swing.JFrame {

    /**
     * Creates new form RecordVisit
     */
    public RecordTreatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_RecordTreatment_Treatment = new javax.swing.JLabel();
        TxtFld_RecordTreatment_Treatment = new javax.swing.JTextField();
        TxtFld_RecordTreatment_Cost = new javax.swing.JTextField();
        Lbl_RecordTreatment_Cost = new javax.swing.JLabel();
        Btn_RecordTreatment_Record = new javax.swing.JButton();
        Btn_RecordTreatment_Cancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Lbl_RecordTreatment_Treatment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RecordTreatment_Treatment.setText("Treatment");

        TxtFld_RecordTreatment_Treatment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtFld_RecordTreatment_Treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_RecordTreatment_TreatmentActionPerformed(evt);
            }
        });

        TxtFld_RecordTreatment_Cost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtFld_RecordTreatment_Cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_RecordTreatment_CostActionPerformed(evt);
            }
        });

        Lbl_RecordTreatment_Cost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RecordTreatment_Cost.setText("Cost");

        Btn_RecordTreatment_Record.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_RecordTreatment_Record.setText("Record");
        Btn_RecordTreatment_Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RecordTreatment_RecordActionPerformed(evt);
            }
        });

        Btn_RecordTreatment_Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_RecordTreatment_Cancel.setText("Cancel");
        Btn_RecordTreatment_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RecordTreatment_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Lbl_RecordTreatment_Treatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Lbl_RecordTreatment_Cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TxtFld_RecordTreatment_Treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TxtFld_RecordTreatment_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(Btn_RecordTreatment_Record)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Btn_RecordTreatment_Cancel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_RecordTreatment_Treatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_RecordTreatment_Treatment))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TxtFld_RecordTreatment_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_RecordTreatment_Cost))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Btn_RecordTreatment_Record)
                                        .addComponent(Btn_RecordTreatment_Cancel))
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void TxtFld_RecordTreatment_TreatmentActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TxtFld_RecordTreatment_CostActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Btn_RecordTreatment_RecordActionPerformed(java.awt.event.ActionEvent evt) {
        treatment = TxtFld_RecordTreatment_Treatment.getText();
        costStr = TxtFld_RecordTreatment_Cost.getText();
        cost = new BigDecimal(costStr.replaceAll(",",""));
        Treatment treatObj = new Treatment(appObj,treatment,cost);
        appObj.updatePatientSeen(true);
        setVisible(false);
    }

    private void Btn_RecordTreatment_CancelActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
    }

    public void setTreatment(Appointment app) {
        appObj = app;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JToggleButton Btn_RecordTreatment_Cancel;
    private javax.swing.JButton Btn_RecordTreatment_Record;
    private javax.swing.JLabel Lbl_RecordTreatment_Cost;
    private javax.swing.JLabel Lbl_RecordTreatment_Treatment;
    private javax.swing.JTextField TxtFld_RecordTreatment_Cost;
    private javax.swing.JTextField TxtFld_RecordTreatment_Treatment;
    private javax.swing.JPanel jPanel1;
    private String treatment;
    private BigDecimal cost;
    private String costStr;
    private Appointment appObj;
    // End of variables declaration
}
