/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group;

/**
 *
 * @author Abigail
 */
public class RegisterPatient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPatient
     */
    public RegisterPatient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterPatientPanel = new javax.swing.JPanel();
        Lbl_RegisterPatient_Title = new javax.swing.JLabel();
        TxtFld_RegisterPatient_Title = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Forename = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Surname = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Dob = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Contact = new javax.swing.JTextField();
        TxtFld_RegisterPatient_House = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Street = new javax.swing.JTextField();
        TxtFld_RegisterPatient_City = new javax.swing.JTextField();
        TxtFld_RegisterPatient_District = new javax.swing.JTextField();
        TxtFld_RegisterPatient_Postcode = new javax.swing.JTextField();
        Lbl_RegisterPatient_Forename = new javax.swing.JLabel();
        Lbl_RegisterPatient_Surname = new javax.swing.JLabel();
        Lbl_RegisterPatient_Dob = new javax.swing.JLabel();
        Lbl_RegisterPatient_Contact = new javax.swing.JLabel();
        Lbl_RegisterPatient_House = new javax.swing.JLabel();
        Lbl_RegisterPatient_Street = new javax.swing.JLabel();
        Lbl_RegisterPatient_City = new javax.swing.JLabel();
        Lbl_RegisterPatient_District = new javax.swing.JLabel();
        Lbl_RegisterPatient_Postcode = new javax.swing.JLabel();
        Btn_RegisterPatient_Cancel = new javax.swing.JButton();
        Btn_RegisterPatient_Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Patient");

        Lbl_RegisterPatient_Title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Title.setText("Title");

        TxtFld_RegisterPatient_Title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_Forename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtFld_RegisterPatient_Forename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_RegisterPatient_ForenameActionPerformed(evt);
            }
        });

        TxtFld_RegisterPatient_Surname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_Dob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtFld_RegisterPatient_Dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_RegisterPatient_DobActionPerformed(evt);
            }
        });

        TxtFld_RegisterPatient_Contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_House.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_Street.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtFld_RegisterPatient_City.setToolTipText("");

        TxtFld_RegisterPatient_District.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TxtFld_RegisterPatient_Postcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Lbl_RegisterPatient_Forename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Forename.setText("Forename");

        Lbl_RegisterPatient_Surname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Surname.setText("Surname");

        Lbl_RegisterPatient_Dob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Dob.setText("Date of Birth");

        Lbl_RegisterPatient_Contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Contact.setText("Contact No.");

        Lbl_RegisterPatient_House.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_House.setText("House No.");

        Lbl_RegisterPatient_Street.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Street.setText("Street");

        Lbl_RegisterPatient_City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_City.setText("City");

        Lbl_RegisterPatient_District.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_District.setText("District");

        Lbl_RegisterPatient_Postcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl_RegisterPatient_Postcode.setText("Postcode");

        Btn_RegisterPatient_Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_RegisterPatient_Cancel.setText("Cancel");

        Btn_RegisterPatient_Submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_RegisterPatient_Submit.setText("Submit");

        javax.swing.GroupLayout RegisterPatientPanelLayout = new javax.swing.GroupLayout(RegisterPatientPanel);
        RegisterPatientPanel.setLayout(RegisterPatientPanelLayout);
        RegisterPatientPanelLayout.setHorizontalGroup(
            RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPatientPanelLayout.createSequentialGroup()
                        .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lbl_RegisterPatient_Dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_Forename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterPatientPanelLayout.createSequentialGroup()
                                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtFld_RegisterPatient_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtFld_RegisterPatient_Forename, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(TxtFld_RegisterPatient_Contact))
                                .addGap(34, 34, 34)
                                .addComponent(Lbl_RegisterPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtFld_RegisterPatient_Dob, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFld_RegisterPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterPatientPanelLayout.createSequentialGroup()
                        .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lbl_RegisterPatient_House, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_Street, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_City, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_District, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_RegisterPatient_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtFld_RegisterPatient_House, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtFld_RegisterPatient_City)
                                .addComponent(TxtFld_RegisterPatient_District)
                                .addComponent(TxtFld_RegisterPatient_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtFld_RegisterPatient_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPatientPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_RegisterPatient_Submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_RegisterPatient_Cancel)
                .addContainerGap())
        );
        RegisterPatientPanelLayout.setVerticalGroup(
            RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Forename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Forename)
                    .addComponent(TxtFld_RegisterPatient_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Surname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Dob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Contact))
                .addGap(18, 18, 18)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_House, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_House))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Street))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_City))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_District, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_District))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFld_RegisterPatient_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_RegisterPatient_Postcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_RegisterPatient_Cancel)
                    .addComponent(Btn_RegisterPatient_Submit))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFld_RegisterPatient_ForenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFld_RegisterPatient_ForenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFld_RegisterPatient_ForenameActionPerformed

    private void TxtFld_RegisterPatient_DobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFld_RegisterPatient_DobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFld_RegisterPatient_DobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_RegisterPatient_Cancel;
    private javax.swing.JButton Btn_RegisterPatient_Submit;
    private javax.swing.JLabel Lbl_RegisterPatient_City;
    private javax.swing.JLabel Lbl_RegisterPatient_Contact;
    private javax.swing.JLabel Lbl_RegisterPatient_District;
    private javax.swing.JLabel Lbl_RegisterPatient_Dob;
    private javax.swing.JLabel Lbl_RegisterPatient_Forename;
    private javax.swing.JLabel Lbl_RegisterPatient_House;
    private javax.swing.JLabel Lbl_RegisterPatient_Postcode;
    private javax.swing.JLabel Lbl_RegisterPatient_Street;
    private javax.swing.JLabel Lbl_RegisterPatient_Surname;
    private javax.swing.JLabel Lbl_RegisterPatient_Title;
    private javax.swing.JPanel RegisterPatientPanel;
    private javax.swing.JTextField TxtFld_RegisterPatient_City;
    private javax.swing.JTextField TxtFld_RegisterPatient_Contact;
    private javax.swing.JTextField TxtFld_RegisterPatient_District;
    private javax.swing.JTextField TxtFld_RegisterPatient_Dob;
    private javax.swing.JTextField TxtFld_RegisterPatient_Forename;
    private javax.swing.JTextField TxtFld_RegisterPatient_House;
    private javax.swing.JTextField TxtFld_RegisterPatient_Postcode;
    private javax.swing.JTextField TxtFld_RegisterPatient_Street;
    private javax.swing.JTextField TxtFld_RegisterPatient_Surname;
    private javax.swing.JTextField TxtFld_RegisterPatient_Title;
    // End of variables declaration//GEN-END:variables
}
